services:
  nextjs:
    image: nextjs-prod
    container_name: nextjs-prod
    build:
      context: ./dockerfiles/nextjs
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    env_file:
      - .env
    tty: true
    networks:
      - shared-network

  python:
    image: python
    container_name: python
    build:
      context: ./dockerfiles/python
      dockerfile: Dockerfile
      args:
        - TZ=$TZ
    ports:
      - 3308:3308
    env_file:
      - .env
    tty: true

networks:
  shared-network:
    external: true
