services:
  nextjs:
    container_name: nextjs-dev
    build:
      context: ./dockerfiles/nextjs
      dockerfile: Dockerfile.dev
      args:
        - DATABASE_URL=$DATABASE_URL
        - GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
        - GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
        - NEXTAUTH_URL=$NEXTAUTH_URL
        - NEXTAUTH_SECRET=$NEXTAUTH_SECRET
        - GMAIL_USER=$GMAIL_USER
        - GMAIL_PASSWORD=$GMAIL_PASSWORD
    ports:
      - 3000:3000
    volumes:
      - ./dockerfiles/nextjs:/app
      - front_node_modules:/app/node_modules
    tty: true

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3307:3306
    env_file:
      - .env
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  front_node_modules:
  db-volume:
