services:
  nextjs:
    build:
      context: ./dockerfiles/nextjs
      dockerfile: Dockerfile.prod
      args:
        - DATABASE_URL=$DATABASE_URL
        - GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
        - GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
        - NEXTAUTH_URL=$NEXTAUTH_URL
        - NEXTAUTH_SECRET=$NEXTAUTH_SECRET
        - GMAIL_USER=$GMAIL_USER
        - GMAIL_PASSWORD=$GMAIL_PASSWORD
    ports:
      - 3000:3000
    volumes:
      - ./dockerfiles/nextjs:/app

  nginx:
    build: ./dockerfiles/nginx
    ports:
      - 80:80
    volumes:
      - ./dockerfiles/nginx:/etc/nginx/