services:
  nginx:
    image: nginx:1.23.3
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./dockerfiles/nginx:/etc/nginx/conf.d
    depends_on:
      - nextjs

  nextjs:
    image: nextjs-prod
    container_name: nextjs-prod
    build:
      context: ./dockerfiles/nextjs
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    env_file:
      - .env
    tty: true