# Variable used to convert value in database into readable one for users
currencies = [
    {"name": "AED", "value": "rate_aed", "label": "United Arab Emirates Dirham"},
    {"name": "AFN", "value": "rate_afn", "label": "Afghan Afghani"},
    {"name": "ALL", "value": "rate_all", "label": "Albanian Lek"},
    {"name": "AMD", "value": "rate_amd", "label": "Armenian Dram"},
    {"name": "ANG", "value": "rate_ang", "label": "Netherlands Antillean Guilder"},
    {"name": "AOA", "value": "rate_aoa", "label": "Angolan Kwanza"},
    {"name": "ARS", "value": "rate_ars", "label": "Argentine Peso"},
    {"name": "AUD", "value": "rate_aud", "label": "Australian Dollar"},
    {"name": "AWG", "value": "rate_awg", "label": "Aruban Florin"},
    {"name": "AZN", "value": "rate_azn", "label": "Azerbaijani Manat"},
    {
        "name": "BAM",
        "value": "rate_bam",
        "label": "Bosnia-Herzegovina Convertible Mark",
    },
    {"name": "BBD", "value": "rate_bbd", "label": "Barbadian Dollar"},
    {"name": "BDT", "value": "rate_bdt", "label": "Bangladeshi Taka"},
    {"name": "BGN", "value": "rate_bgn", "label": "Bulgarian Lev"},
    {"name": "BHD", "value": "rate_bhd", "label": "Bahraini Dinar"},
    {"name": "BIF", "value": "rate_bif", "label": "Burundian Franc"},
    {"name": "BMD", "value": "rate_bmd", "label": "Bermudan Dollar"},
    {"name": "BND", "value": "rate_bnd", "label": "Brunei Dollar"},
    {"name": "BOB", "value": "rate_bob", "label": "Bolivian Boliviano"},
    {"name": "BRL", "value": "rate_brl", "label": "Brazilian Real"},
    {"name": "BSD", "value": "rate_bsd", "label": "Bahamian Dollar"},
    {"name": "BTC", "value": "rate_btc", "label": "Bitcoin"},
    {"name": "BTN", "value": "rate_btn", "label": "Bhutanese Ngultrum"},
    {"name": "BWP", "value": "rate_bwp", "label": "Botswanan Pula"},
    {"name": "BYN", "value": "rate_byn", "label": "New Belarusian Ruble"},
    {"name": "BYR", "value": "rate_byr", "label": "Belarusian Ruble"},
    {"name": "BZD", "value": "rate_bzd", "label": "Belize Dollar"},
    {"name": "CAD", "value": "rate_cad", "label": "Canadian Dollar"},
    {"name": "CDF", "value": "rate_cdf", "label": "Congolese Franc"},
    {"name": "CHF", "value": "rate_chf", "label": "Swiss Franc"},
    {"name": "CLF", "value": "rate_clf", "label": "Chilean Unit of Account (UF)"},
    {"name": "CLP", "value": "rate_clp", "label": "Chilean Peso"},
    {"name": "CNY", "value": "rate_cny", "label": "Chinese Yuan"},
    {"name": "COP", "value": "rate_cop", "label": "Colombian Peso"},
    {"name": "CRC", "value": "rate_crc", "label": "Costa Rican Col\u00f3n"},
    {"name": "CUC", "value": "rate_cuc", "label": "Cuban Convertible Peso"},
    {"name": "CUP", "value": "rate_cup", "label": "Cuban Peso"},
    {"name": "CVE", "value": "rate_cve", "label": "Cape Verdean Escudo"},
    {"name": "CZK", "value": "rate_czk", "label": "Czech Republic Koruna"},
    {"name": "DJF", "value": "rate_djf", "label": "Djiboutian Franc"},
    {"name": "DKK", "value": "rate_dkk", "label": "Danish Krone"},
    {"name": "DOP", "value": "rate_dop", "label": "Dominican Peso"},
    {"name": "DZD", "value": "rate_dzd", "label": "Algerian Dinar"},
    {"name": "EGP", "value": "rate_egp", "label": "Egyptian Pound"},
    {"name": "ERN", "value": "rate_ern", "label": "Eritrean Nakfa"},
    {"name": "ETB", "value": "rate_etb", "label": "Ethiopian Birr"},
    {"name": "EUR", "value": "rate_eur", "label": "Euro"},
    {"name": "FJD", "value": "rate_fjd", "label": "Fijian Dollar"},
    {"name": "FKP", "value": "rate_fkp", "label": "Falkland Islands Pound"},
    {"name": "GBP", "value": "rate_gbp", "label": "British Pound Sterling"},
    {"name": "GEL", "value": "rate_gel", "label": "Georgian Lari"},
    {"name": "GGP", "value": "rate_ggp", "label": "Guernsey Pound"},
    {"name": "GHS", "value": "rate_ghs", "label": "Ghanaian Cedi"},
    {"name": "GIP", "value": "rate_gip", "label": "Gibraltar Pound"},
    {"name": "GMD", "value": "rate_gmd", "label": "Gambian Dalasi"},
    {"name": "GNF", "value": "rate_gnf", "label": "Guinean Franc"},
    {"name": "GTQ", "value": "rate_gtq", "label": "Guatemalan Quetzal"},
    {"name": "GYD", "value": "rate_gyd", "label": "Guyanaese Dollar"},
    {"name": "HKD", "value": "rate_hkd", "label": "Hong Kong Dollar"},
    {"name": "HNL", "value": "rate_hnl", "label": "Honduran Lempira"},
    {"name": "HRK", "value": "rate_hrk", "label": "Croatian Kuna"},
    {"name": "HTG", "value": "rate_htg", "label": "Haitian Gourde"},
    {"name": "HUF", "value": "rate_huf", "label": "Hungarian Forint"},
    {"name": "IDR", "value": "rate_idr", "label": "Indonesian Rupiah"},
    {"name": "ILS", "value": "rate_ils", "label": "Israeli New Sheqel"},
    {"name": "IMP", "value": "rate_imp", "label": "Manx pound"},
    {"name": "INR", "value": "rate_inr", "label": "Indian Rupee"},
    {"name": "IQD", "value": "rate_iqd", "label": "Iraqi Dinar"},
    {"name": "IRR", "value": "rate_irr", "label": "Iranian Rial"},
    {"name": "ISK", "value": "rate_isk", "label": "Icelandic Kr\u00f3na"},
    {"name": "JEP", "value": "rate_jep", "label": "Jersey Pound"},
    {"name": "JMD", "value": "rate_jmd", "label": "Jamaican Dollar"},
    {"name": "JOD", "value": "rate_jod", "label": "Jordanian Dinar"},
    {"name": "JPY", "value": "rate_jpy", "label": "Japanese Yen"},
    {"name": "KES", "value": "rate_kes", "label": "Kenyan Shilling"},
    {"name": "KGS", "value": "rate_kgs", "label": "Kyrgystani Som"},
    {"name": "KHR", "value": "rate_khr", "label": "Cambodian Riel"},
    {"name": "KMF", "value": "rate_kmf", "label": "Comorian Franc"},
    {"name": "KPW", "value": "rate_kpw", "label": "North Korean Won"},
    {"name": "KRW", "value": "rate_krw", "label": "South Korean Won"},
    {"name": "KWD", "value": "rate_kwd", "label": "Kuwaiti Dinar"},
    {"name": "KYD", "value": "rate_kyd", "label": "Cayman Islands Dollar"},
    {"name": "KZT", "value": "rate_kzt", "label": "Kazakhstani Tenge"},
    {"name": "LAK", "value": "rate_lak", "label": "Laotian Kip"},
    {"name": "LBP", "value": "rate_lbp", "label": "Lebanese Pound"},
    {"name": "LKR", "value": "rate_lkr", "label": "Sri Lankan Rupee"},
    {"name": "LRD", "value": "rate_lrd", "label": "Liberian Dollar"},
    {"name": "LSL", "value": "rate_lsl", "label": "Lesotho Loti"},
    {"name": "LTL", "value": "rate_ltl", "label": "Lithuanian Litas"},
    {"name": "LVL", "value": "rate_lvl", "label": "Latvian Lats"},
    {"name": "LYD", "value": "rate_lyd", "label": "Libyan Dinar"},
    {"name": "MAD", "value": "rate_mad", "label": "Moroccan Dirham"},
    {"name": "MDL", "value": "rate_mdl", "label": "Moldovan Leu"},
    {"name": "MGA", "value": "rate_mga", "label": "Malagasy Ariary"},
    {"name": "MKD", "value": "rate_mkd", "label": "Macedonian Denar"},
    {"name": "MMK", "value": "rate_mmk", "label": "Myanma Kyat"},
    {"name": "MNT", "value": "rate_mnt", "label": "Mongolian Tugrik"},
    {"name": "MOP", "value": "rate_mop", "label": "Macanese Pataca"},
    {"name": "MRO", "value": "rate_mro", "label": "Mauritanian Ouguiya"},
    {"name": "MUR", "value": "rate_mur", "label": "Mauritian Rupee"},
    {"name": "MVR", "value": "rate_mvr", "label": "Maldivian Rufiyaa"},
    {"name": "MWK", "value": "rate_mwk", "label": "Malawian Kwacha"},
    {"name": "MXN", "value": "rate_mxn", "label": "Mexican Peso"},
    {"name": "MYR", "value": "rate_myr", "label": "Malaysian Ringgit"},
    {"name": "MZN", "value": "rate_mzn", "label": "Mozambican Metical"},
    {"name": "NAD", "value": "rate_nad", "label": "Namibian Dollar"},
    {"name": "NGN", "value": "rate_ngn", "label": "Nigerian Naira"},
    {"name": "NIO", "value": "rate_nio", "label": "Nicaraguan C\u00f3rdoba"},
    {"name": "NOK", "value": "rate_nok", "label": "Norwegian Krone"},
    {"name": "NPR", "value": "rate_npr", "label": "Nepalese Rupee"},
    {"name": "NZD", "value": "rate_nzd", "label": "New Zealand Dollar"},
    {"name": "OMR", "value": "rate_omr", "label": "Omani Rial"},
    {"name": "PAB", "value": "rate_pab", "label": "Panamanian Balboa"},
    {"name": "PEN", "value": "rate_pen", "label": "Peruvian Nuevo Sol"},
    {"name": "PGK", "value": "rate_pgk", "label": "Papua New Guinean Kina"},
    {"name": "PHP", "value": "rate_php", "label": "Philippine Peso"},
    {"name": "PKR", "value": "rate_pkr", "label": "Pakistani Rupee"},
    {"name": "PLN", "value": "rate_pln", "label": "Polish Zloty"},
    {"name": "PYG", "value": "rate_pyg", "label": "Paraguayan Guarani"},
    {"name": "QAR", "value": "rate_qar", "label": "Qatari Rial"},
    {"name": "RON", "value": "rate_ron", "label": "Romanian Leu"},
    {"name": "RSD", "value": "rate_rsd", "label": "Serbian Dinar"},
    {"name": "RUB", "value": "rate_rub", "label": "Russian Ruble"},
    {"name": "RWF", "value": "rate_rwf", "label": "Rwandan Franc"},
    {"name": "SAR", "value": "rate_sar", "label": "Saudi Riyal"},
    {"name": "SBD", "value": "rate_sbd", "label": "Solomon Islands Dollar"},
    {"name": "SCR", "value": "rate_scr", "label": "Seychellois Rupee"},
    {"name": "SDG", "value": "rate_sdg", "label": "Sudanese Pound"},
    {"name": "SEK", "value": "rate_sek", "label": "Swedish Krona"},
    {"name": "SGD", "value": "rate_sgd", "label": "Singapore Dollar"},
    {"name": "SHP", "value": "rate_shp", "label": "Saint Helena Pound"},
    {"name": "SLE", "value": "rate_sle", "label": "Sierra Leonean Leone"},
    {"name": "SLL", "value": "rate_sll", "label": "Sierra Leonean Leone"},
    {"name": "SOS", "value": "rate_sos", "label": "Somali Shilling"},
    {"name": "SRD", "value": "rate_srd", "label": "Surinamese Dollar"},
    {
        "name": "STD",
        "value": "rate_std",
        "label": "S\u00e3o Tom\u00e9 and Pr\u00edncipe Dobra",
    },
    {"name": "SVC", "value": "rate_svc", "label": "Salvadoran Col\u00f3n"},
    {"name": "SYP", "value": "rate_syp", "label": "Syrian Pound"},
    {"name": "SZL", "value": "rate_szl", "label": "Swazi Lilangeni"},
    {"name": "THB", "value": "rate_thb", "label": "Thai Baht"},
    {"name": "TJS", "value": "rate_tjs", "label": "Tajikistani Somoni"},
    {"name": "TMT", "value": "rate_tmt", "label": "Turkmenistani Manat"},
    {"name": "TND", "value": "rate_tnd", "label": "Tunisian Dinar"},
    {"name": "TOP", "value": "rate_top", "label": "Tongan Pa\u02bbanga"},
    {"name": "TRY", "value": "rate_try", "label": "Turkish Lira"},
    {"name": "TTD", "value": "rate_ttd", "label": "Trinidad and Tobago Dollar"},
    {"name": "TWD", "value": "rate_twd", "label": "New Taiwan Dollar"},
    {"name": "TZS", "value": "rate_tzs", "label": "Tanzanian Shilling"},
    {"name": "UAH", "value": "rate_uah", "label": "Ukrainian Hryvnia"},
    {"name": "UGX", "value": "rate_ugx", "label": "Ugandan Shilling"},
    {"name": "USD", "value": "rate_usd", "label": "United States Dollar"},
    {"name": "UYU", "value": "rate_uyu", "label": "Uruguayan Peso"},
    {"name": "UZS", "value": "rate_uzs", "label": "Uzbekistan Som"},
    {"name": "VEF", "value": "rate_vef", "label": "Venezuelan Bol\u00edvar Fuerte"},
    {"name": "VES", "value": "rate_ves", "label": "Sovereign Bolivar"},
    {"name": "VND", "value": "rate_vnd", "label": "Vietnamese Dong"},
    {"name": "VUV", "value": "rate_vuv", "label": "Vanuatu Vatu"},
    {"name": "WST", "value": "rate_wst", "label": "Samoan Tala"},
    {"name": "XAF", "value": "rate_xaf", "label": "CFA Franc BEAC"},
    {"name": "XAG", "value": "rate_xag", "label": "Silver (troy ounce)"},
    {"name": "XAU", "value": "rate_xau", "label": "Gold (troy ounce)"},
    {"name": "XCD", "value": "rate_xcd", "label": "East Caribbean Dollar"},
    {"name": "XDR", "value": "rate_xdr", "label": "Special Drawing Rights"},
    {"name": "XOF", "value": "rate_xof", "label": "CFA Franc BCEAO"},
    {"name": "XPF", "value": "rate_xpf", "label": "CFP Franc"},
    {"name": "YER", "value": "rate_yer", "label": "Yemeni Rial"},
    {"name": "ZAR", "value": "rate_zar", "label": "South African Rand"},
    {"name": "ZMK", "value": "rate_zmk", "label": "Zambian Kwacha (pre-2013)"},
    {"name": "ZMW", "value": "rate_zmw", "label": "Zambian Kwacha"},
    {"name": "ZWL", "value": "rate_zwl", "label": "Zimbabwean Dollar"},
]
