# The base image is node:18.13.0
FROM node:18.13.0

# Set the working directory
WORKDIR /app

# Copy the package.json files to the working directory and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application files and generate Prisma client
COPY . .
RUN npx prisma generate

# Start the development server
CMD [ "npm", "run", "dev" ]