import React, { Dispatch, SetStateAction } from "react";
import Select, { SingleValue } from "react-select";
import styles from "../styles/Selectbox.module.css";

interface Props {
  setCurrency: Dispatch<SetStateAction<string | null>>;
}

interface SelectedOption {
  value: string;
  label: string;
}

const Selectbox = (props: Props) => {
  const currencies = [
    { value: "rate_aed", label: "AED: United Arab Emirates Dirham" },
    { value: "rate_afn", label: "AFN: Afghan Afghani" },
    { value: "rate_all", label: "ALL: Albanian Lek" },
    { value: "rate_amd", label: "AMD: Armenian Dram" },
    { value: "rate_ang", label: "ANG: Netherlands Antillean Guilder" },
    { value: "rate_aoa", label: "AOA: Angolan Kwanza" },
    { value: "rate_ars", label: "ARS: Argentine Peso" },
    { value: "rate_aud", label: "AUD: Australian Dollar" },
    { value: "rate_awg", label: "AWG: Aruban Florin" },
    { value: "rate_azn", label: "AZN: Azerbaijani Manat" },
    { value: "rate_bam", label: "BAM: Bosnia-Herzegovina Convertible Mark" },
    { value: "rate_bbd", label: "BBD: Barbadian Dollar" },
    { value: "rate_bdt", label: "BDT: Bangladeshi Taka" },
    { value: "rate_bgn", label: "BGN: Bulgarian Lev" },
    { value: "rate_bhd", label: "BHD: Bahraini Dinar" },
    { value: "rate_bif", label: "BIF: Burundian Franc" },
    { value: "rate_bmd", label: "BMD: Bermudan Dollar" },
    { value: "rate_bnd", label: "BND: Brunei Dollar" },
    { value: "rate_bob", label: "BOB: Bolivian Boliviano" },
    { value: "rate_brl", label: "BRL: Brazilian Real" },
    { value: "rate_bsd", label: "BSD: Bahamian Dollar" },
    { value: "rate_btc", label: "BTC: Bitcoin" },
    { value: "rate_btn", label: "BTN: Bhutanese Ngultrum" },
    { value: "rate_bwp", label: "BWP: Botswanan Pula" },
    { value: "rate_byn", label: "BYN: New Belarusian Ruble" },
    { value: "rate_byr", label: "BYR: Belarusian Ruble" },
    { value: "rate_bzd", label: "BZD: Belize Dollar" },
    { value: "rate_cad", label: "CAD: Canadian Dollar" },
    { value: "rate_cdf", label: "CDF: Congolese Franc" },
    { value: "rate_chf", label: "CHF: Swiss Franc" },
    { value: "rate_clf", label: "CLF: Chilean Unit of Account (UF)" },
    { value: "rate_clp", label: "CLP: Chilean Peso" },
    { value: "rate_cny", label: "CNY: Chinese Yuan" },
    { value: "rate_cop", label: "COP: Colombian Peso" },
    { value: "rate_crc", label: "CRC: Costa Rican Col\u00f3n" },
    { value: "rate_cuc", label: "CUC: Cuban Convertible Peso" },
    { value: "rate_cup", label: "CUP: Cuban Peso" },
    { value: "rate_cve", label: "CVE: Cape Verdean Escudo" },
    { value: "rate_czk", label: "CZK: Czech Republic Koruna" },
    { value: "rate_djf", label: "DJF: Djiboutian Franc" },
    { value: "rate_dkk", label: "DKK: Danish Krone" },
    { value: "rate_dop", label: "DOP: Dominican Peso" },
    { value: "rate_dzd", label: "DZD: Algerian Dinar" },
    { value: "rate_egp", label: "EGP: Egyptian Pound" },
    { value: "rate_ern", label: "ERN: Eritrean Nakfa" },
    { value: "rate_etb", label: "ETB: Ethiopian Birr" },
    { value: "rate_eur", label: "EUR: Euro" },
    { value: "rate_fjd", label: "FJD: Fijian Dollar" },
    { value: "rate_fkp", label: "FKP: Falkland Islands Pound" },
    { value: "rate_gbp", label: "GBP: British Pound Sterling" },
    { value: "rate_gel", label: "GEL: Georgian Lari" },
    { value: "rate_ggp", label: "GGP: Guernsey Pound" },
    { value: "rate_ghs", label: "GHS: Ghanaian Cedi" },
    { value: "rate_gip", label: "GIP: Gibraltar Pound" },
    { value: "rate_gmd", label: "GMD: Gambian Dalasi" },
    { value: "rate_gnf", label: "GNF: Guinean Franc" },
    { value: "rate_gtq", label: "GTQ: Guatemalan Quetzal" },
    { value: "rate_gyd", label: "GYD: Guyanaese Dollar" },
    { value: "rate_hkd", label: "HKD: Hong Kong Dollar" },
    { value: "rate_hnl", label: "HNL: Honduran Lempira" },
    { value: "rate_hrk", label: "HRK: Croatian Kuna" },
    { value: "rate_htg", label: "HTG: Haitian Gourde" },
    { value: "rate_huf", label: "HUF: Hungarian Forint" },
    { value: "rate_idr", label: "IDR: Indonesian Rupiah" },
    { value: "rate_ils", label: "ILS: Israeli New Sheqel" },
    { value: "rate_imp", label: "IMP: Manx pound" },
    { value: "rate_inr", label: "INR: Indian Rupee" },
    { value: "rate_iqd", label: "IQD: Iraqi Dinar" },
    { value: "rate_irr", label: "IRR: Iranian Rial" },
    { value: "rate_isk", label: "ISK: Icelandic Kr\u00f3na" },
    { value: "rate_jep", label: "JEP: Jersey Pound" },
    { value: "rate_jmd", label: "JMD: Jamaican Dollar" },
    { value: "rate_jod", label: "JOD: Jordanian Dinar" },
    { value: "rate_jpy", label: "JPY: Japanese Yen" },
    { value: "rate_kes", label: "KES: Kenyan Shilling" },
    { value: "rate_kgs", label: "KGS: Kyrgystani Som" },
    { value: "rate_khr", label: "KHR: Cambodian Riel" },
    { value: "rate_kmf", label: "KMF: Comorian Franc" },
    { value: "rate_kpw", label: "KPW: North Korean Won" },
    { value: "rate_krw", label: "KRW: South Korean Won" },
    { value: "rate_kwd", label: "KWD: Kuwaiti Dinar" },
    { value: "rate_kyd", label: "KYD: Cayman Islands Dollar" },
    { value: "rate_kzt", label: "KZT: Kazakhstani Tenge" },
    { value: "rate_lak", label: "LAK: Laotian Kip" },
    { value: "rate_lbp", label: "LBP: Lebanese Pound" },
    { value: "rate_lkr", label: "LKR: Sri Lankan Rupee" },
    { value: "rate_lrd", label: "LRD: Liberian Dollar" },
    { value: "rate_lsl", label: "LSL: Lesotho Loti" },
    { value: "rate_ltl", label: "LTL: Lithuanian Litas" },
    { value: "rate_lvl", label: "LVL: Latvian Lats" },
    { value: "rate_lyd", label: "LYD: Libyan Dinar" },
    { value: "rate_mad", label: "MAD: Moroccan Dirham" },
    { value: "rate_mdl", label: "MDL: Moldovan Leu" },
    { value: "rate_mga", label: "MGA: Malagasy Ariary" },
    { value: "rate_mkd", label: "MKD: Macedonian Denar" },
    { value: "rate_mmk", label: "MMK: Myanma Kyat" },
    { value: "rate_mnt", label: "MNT: Mongolian Tugrik" },
    { value: "rate_mop", label: "MOP: Macanese Pataca" },
    { value: "rate_mro", label: "MRO: Mauritanian Ouguiya" },
    { value: "rate_mur", label: "MUR: Mauritian Rupee" },
    { value: "rate_mvr", label: "MVR: Maldivian Rufiyaa" },
    { value: "rate_mwk", label: "MWK: Malawian Kwacha" },
    { value: "rate_mxn", label: "MXN: Mexican Peso" },
    { value: "rate_myr", label: "MYR: Malaysian Ringgit" },
    { value: "rate_mzn", label: "MZN: Mozambican Metical" },
    { value: "rate_nad", label: "NAD: Namibian Dollar" },
    { value: "rate_ngn", label: "NGN: Nigerian Naira" },
    { value: "rate_nio", label: "NIO: Nicaraguan C\u00f3rdoba" },
    { value: "rate_nok", label: "NOK: Norwegian Krone" },
    { value: "rate_npr", label: "NPR: Nepalese Rupee" },
    { value: "rate_nzd", label: "NZD: New Zealand Dollar" },
    { value: "rate_omr", label: "OMR: Omani Rial" },
    { value: "rate_pab", label: "PAB: Panamanian Balboa" },
    { value: "rate_pen", label: "PEN: Peruvian Nuevo Sol" },
    { value: "rate_pgk", label: "PGK: Papua New Guinean Kina" },
    { value: "rate_php", label: "PHP: Philippine Peso" },
    { value: "rate_pkr", label: "PKR: Pakistani Rupee" },
    { value: "rate_pln", label: "PLN: Polish Zloty" },
    { value: "rate_pyg", label: "PYG: Paraguayan Guarani" },
    { value: "rate_qar", label: "QAR: Qatari Rial" },
    { value: "rate_ron", label: "RON: Romanian Leu" },
    { value: "rate_rsd", label: "RSD: Serbian Dinar" },
    { value: "rate_rub", label: "RUB: Russian Ruble" },
    { value: "rate_rwf", label: "RWF: Rwandan Franc" },
    { value: "rate_sar", label: "SAR: Saudi Riyal" },
    { value: "rate_sbd", label: "SBD: Solomon Islands Dollar" },
    { value: "rate_scr", label: "SCR: Seychellois Rupee" },
    { value: "rate_sdg", label: "SDG: Sudanese Pound" },
    { value: "rate_sek", label: "SEK: Swedish Krona" },
    { value: "rate_sgd", label: "SGD: Singapore Dollar" },
    { value: "rate_shp", label: "SHP: Saint Helena Pound" },
    { value: "rate_sle", label: "SLE: Sierra Leonean Leone" },
    { value: "rate_sll", label: "SLL: Sierra Leonean Leone" },
    { value: "rate_sos", label: "SOS: Somali Shilling" },
    { value: "rate_srd", label: "SRD: Surinamese Dollar" },
    {
      value: "rate_std",
      label: "STD: S\u00e3o Tom\u00e9 and Pr\u00edncipe Dobra",
    },
    { value: "rate_svc", label: "SVC: Salvadoran Col\u00f3n" },
    { value: "rate_syp", label: "SYP: Syrian Pound" },
    { value: "rate_szl", label: "SZL: Swazi Lilangeni" },
    { value: "rate_thb", label: "THB: Thai Baht" },
    { value: "rate_tjs", label: "TJS: Tajikistani Somoni" },
    { value: "rate_tmt", label: "TMT: Turkmenistani Manat" },
    { value: "rate_tnd", label: "TND: Tunisian Dinar" },
    { value: "rate_top", label: "TOP: Tongan Pa\u02bbanga" },
    { value: "rate_try", label: "TRY: Turkish Lira" },
    { value: "rate_ttd", label: "TTD: Trinidad and Tobago Dollar" },
    { value: "rate_twd", label: "TWD: New Taiwan Dollar" },
    { value: "rate_tzs", label: "TZS: Tanzanian Shilling" },
    { value: "rate_uah", label: "UAH: Ukrainian Hryvnia" },
    { value: "rate_ugx", label: "UGX: Ugandan Shilling" },
    { value: "rate_usd", label: "USD: United States Dollar" },
    { value: "rate_uyu", label: "UYU: Uruguayan Peso" },
    { value: "rate_uzs", label: "UZS: Uzbekistan Som" },
    { value: "rate_vef", label: "VEF: Venezuelan Bol\u00edvar Fuerte" },
    { value: "rate_ves", label: "VES: Sovereign Bolivar" },
    { value: "rate_vnd", label: "VND: Vietnamese Dong" },
    { value: "rate_vuv", label: "VUV: Vanuatu Vatu" },
    { value: "rate_wst", label: "WST: Samoan Tala" },
    { value: "rate_xaf", label: "XAF: CFA Franc BEAC" },
    { value: "rate_xag", label: "XAG: Silver (troy ounce)" },
    { value: "rate_xau", label: "XAU: Gold (troy ounce)" },
    { value: "rate_xcd", label: "XCD: East Caribbean Dollar" },
    { value: "rate_xdr", label: "XDR: Special Drawing Rights" },
    { value: "rate_xof", label: "XOF: CFA Franc BCEAO" },
    { value: "rate_xpf", label: "XPF: CFP Franc" },
    { value: "rate_yer", label: "YER: Yemeni Rial" },
    { value: "rate_zar", label: "ZAR: South African Rand" },
    { value: "rate_zmk", label: "ZMK: Zambian Kwacha (pre-2013)" },
    { value: "rate_zmw", label: "ZMW: Zambian Kwacha" },
    { value: "rate_zwl", label: "ZWL: Zimbabwean Dollar" },
  ];

  return (
    <Select
      className={styles.select}
      options={currencies}
      isSearchable={true}
      onChange={(selectedOption: SingleValue<SelectedOption>) => {
        props.setCurrency(selectedOption!.value)
      }}
    />
  );
};

export default Selectbox;
