-- CreateTable
CREATE TABLE `account` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `userId` INTEGER NOT NULL,
    `type` VARCHAR(191) NOT NULL,
    `provider` VARCHAR(191) NOT NULL,
    `providerAccountId` VARCHAR(191) NOT NULL,
    `refresh_token` TEXT NULL,
    `access_token` TEXT NULL,
    `expires_at` INTEGER NULL,
    `token_type` VARCHAR(191) NULL,
    `scope` VARCHAR(191) NULL,
    `id_token` TEXT NULL,
    `session_state` VARCHAR(191) NULL,

    UNIQUE INDEX `account_provider_providerAccountId_key`(`provider`, `providerAccountId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `session` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `sessionToken` VARCHAR(191) NOT NULL,
    `userId` INTEGER NOT NULL,
    `expires` DATETIME(3) NOT NULL,

    UNIQUE INDEX `session_sessionToken_key`(`sessionToken`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `user` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(191) NULL,
    `email` VARCHAR(191) NULL,
    `emailVerified` DATETIME(3) NULL,
    `image` VARCHAR(191) NULL,

    UNIQUE INDEX `user_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `verificationtoken` (
    `identifier` VARCHAR(191) NOT NULL,
    `token` VARCHAR(191) NOT NULL,
    `expires` DATETIME(3) NOT NULL,

    UNIQUE INDEX `verificationtoken_token_key`(`token`),
    UNIQUE INDEX `verificationtoken_identifier_token_key`(`identifier`, `token`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `userpreference` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `userId` INTEGER NOT NULL,
    `language` VARCHAR(191) NULL,
    `base` VARCHAR(191) NULL,
    `converted` VARCHAR(191) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `exchangerate` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `fetched_datetime` VARCHAR(191) NOT NULL,
    `is_data_fetched` VARCHAR(191) NOT NULL,
    `base_currency` VARCHAR(191) NULL,
    `rate_aed` DOUBLE NULL,
    `rate_afn` DOUBLE NULL,
    `rate_all` DOUBLE NULL,
    `rate_amd` DOUBLE NULL,
    `rate_ang` DOUBLE NULL,
    `rate_aoa` DOUBLE NULL,
    `rate_ars` DOUBLE NULL,
    `rate_aud` DOUBLE NULL,
    `rate_awg` DOUBLE NULL,
    `rate_azn` DOUBLE NULL,
    `rate_bam` DOUBLE NULL,
    `rate_bbd` DOUBLE NULL,
    `rate_bdt` DOUBLE NULL,
    `rate_bgn` DOUBLE NULL,
    `rate_bhd` DOUBLE NULL,
    `rate_bif` DOUBLE NULL,
    `rate_bmd` DOUBLE NULL,
    `rate_bnd` DOUBLE NULL,
    `rate_bob` DOUBLE NULL,
    `rate_brl` DOUBLE NULL,
    `rate_bsd` DOUBLE NULL,
    `rate_btc` DOUBLE NULL,
    `rate_btn` DOUBLE NULL,
    `rate_bwp` DOUBLE NULL,
    `rate_byn` DOUBLE NULL,
    `rate_byr` DOUBLE NULL,
    `rate_bzd` DOUBLE NULL,
    `rate_cad` DOUBLE NULL,
    `rate_cdf` DOUBLE NULL,
    `rate_chf` DOUBLE NULL,
    `rate_clf` DOUBLE NULL,
    `rate_clp` DOUBLE NULL,
    `rate_cny` DOUBLE NULL,
    `rate_cop` DOUBLE NULL,
    `rate_crc` DOUBLE NULL,
    `rate_cuc` DOUBLE NULL,
    `rate_cup` DOUBLE NULL,
    `rate_cve` DOUBLE NULL,
    `rate_czk` DOUBLE NULL,
    `rate_djf` DOUBLE NULL,
    `rate_dkk` DOUBLE NULL,
    `rate_dop` DOUBLE NULL,
    `rate_dzd` DOUBLE NULL,
    `rate_egp` DOUBLE NULL,
    `rate_ern` DOUBLE NULL,
    `rate_etb` DOUBLE NULL,
    `rate_eur` DOUBLE NULL,
    `rate_fjd` DOUBLE NULL,
    `rate_fkp` DOUBLE NULL,
    `rate_gbp` DOUBLE NULL,
    `rate_gel` DOUBLE NULL,
    `rate_ggp` DOUBLE NULL,
    `rate_ghs` DOUBLE NULL,
    `rate_gip` DOUBLE NULL,
    `rate_gmd` DOUBLE NULL,
    `rate_gnf` DOUBLE NULL,
    `rate_gtq` DOUBLE NULL,
    `rate_gyd` DOUBLE NULL,
    `rate_hkd` DOUBLE NULL,
    `rate_hnl` DOUBLE NULL,
    `rate_hrk` DOUBLE NULL,
    `rate_htg` DOUBLE NULL,
    `rate_huf` DOUBLE NULL,
    `rate_idr` DOUBLE NULL,
    `rate_ils` DOUBLE NULL,
    `rate_imp` DOUBLE NULL,
    `rate_inr` DOUBLE NULL,
    `rate_iqd` DOUBLE NULL,
    `rate_irr` DOUBLE NULL,
    `rate_isk` DOUBLE NULL,
    `rate_jep` DOUBLE NULL,
    `rate_jmd` DOUBLE NULL,
    `rate_jod` DOUBLE NULL,
    `rate_jpy` DOUBLE NULL,
    `rate_kes` DOUBLE NULL,
    `rate_kgs` DOUBLE NULL,
    `rate_khr` DOUBLE NULL,
    `rate_kmf` DOUBLE NULL,
    `rate_kpw` DOUBLE NULL,
    `rate_krw` DOUBLE NULL,
    `rate_kwd` DOUBLE NULL,
    `rate_kyd` DOUBLE NULL,
    `rate_kzt` DOUBLE NULL,
    `rate_lak` DOUBLE NULL,
    `rate_lbp` DOUBLE NULL,
    `rate_lkr` DOUBLE NULL,
    `rate_lrd` DOUBLE NULL,
    `rate_lsl` DOUBLE NULL,
    `rate_ltl` DOUBLE NULL,
    `rate_lvl` DOUBLE NULL,
    `rate_lyd` DOUBLE NULL,
    `rate_mad` DOUBLE NULL,
    `rate_mdl` DOUBLE NULL,
    `rate_mga` DOUBLE NULL,
    `rate_mkd` DOUBLE NULL,
    `rate_mmk` DOUBLE NULL,
    `rate_mnt` DOUBLE NULL,
    `rate_mop` DOUBLE NULL,
    `rate_mro` DOUBLE NULL,
    `rate_mur` DOUBLE NULL,
    `rate_mvr` DOUBLE NULL,
    `rate_mwk` DOUBLE NULL,
    `rate_mxn` DOUBLE NULL,
    `rate_myr` DOUBLE NULL,
    `rate_mzn` DOUBLE NULL,
    `rate_nad` DOUBLE NULL,
    `rate_ngn` DOUBLE NULL,
    `rate_nio` DOUBLE NULL,
    `rate_nok` DOUBLE NULL,
    `rate_npr` DOUBLE NULL,
    `rate_nzd` DOUBLE NULL,
    `rate_omr` DOUBLE NULL,
    `rate_pab` DOUBLE NULL,
    `rate_pen` DOUBLE NULL,
    `rate_pgk` DOUBLE NULL,
    `rate_php` DOUBLE NULL,
    `rate_pkr` DOUBLE NULL,
    `rate_pln` DOUBLE NULL,
    `rate_pyg` DOUBLE NULL,
    `rate_qar` DOUBLE NULL,
    `rate_ron` DOUBLE NULL,
    `rate_rsd` DOUBLE NULL,
    `rate_rub` DOUBLE NULL,
    `rate_rwg` DOUBLE NULL,
    `rate_sar` DOUBLE NULL,
    `rate_sbd` DOUBLE NULL,
    `rate_scr` DOUBLE NULL,
    `rate_sdg` DOUBLE NULL,
    `rate_sek` DOUBLE NULL,
    `rate_sgd` DOUBLE NULL,
    `rate_shp` DOUBLE NULL,
    `rate_sle` DOUBLE NULL,
    `rate_sll` DOUBLE NULL,
    `rate_sos` DOUBLE NULL,
    `rate_srd` DOUBLE NULL,
    `rate_std` DOUBLE NULL,
    `rate_svc` DOUBLE NULL,
    `rate_syp` DOUBLE NULL,
    `rate_szl` DOUBLE NULL,
    `rate_thb` DOUBLE NULL,
    `rate_tjs` DOUBLE NULL,
    `rate_tmt` DOUBLE NULL,
    `rate_tnd` DOUBLE NULL,
    `rate_top` DOUBLE NULL,
    `rate_try` DOUBLE NULL,
    `rate_ttd` DOUBLE NULL,
    `rate_twd` DOUBLE NULL,
    `rate_tzs` DOUBLE NULL,
    `rate_uah` DOUBLE NULL,
    `rate_ugx` DOUBLE NULL,
    `rate_usd` DOUBLE NULL,
    `rate_uyu` DOUBLE NULL,
    `rate_uzs` DOUBLE NULL,
    `rate_vef` DOUBLE NULL,
    `rate_ves` DOUBLE NULL,
    `rate_vnd` DOUBLE NULL,
    `rate_vuv` DOUBLE NULL,
    `rate_wst` DOUBLE NULL,
    `rate_xaf` DOUBLE NULL,
    `rate_xag` DOUBLE NULL,
    `rate_xau` DOUBLE NULL,
    `rate_xcd` DOUBLE NULL,
    `rate_xdr` DOUBLE NULL,
    `rate_xof` DOUBLE NULL,
    `rate_xpf` DOUBLE NULL,
    `rate_yer` DOUBLE NULL,
    `rate_zar` DOUBLE NULL,
    `rate_zmk` DOUBLE NULL,
    `rate_zmw` DOUBLE NULL,
    `rate_zwl` DOUBLE NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `account` ADD CONSTRAINT `account_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `session` ADD CONSTRAINT `session_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `userpreference` ADD CONSTRAINT `userpreference_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
